name: s3_migrator
services:
  app:
    container_name : mgr_app
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
      - ./storage/app/files:/var/www/storage/app/files
    networks:
      - app-network
    depends_on:
      - db
      - minio

  queue-worker:
    container_name : mgr_queue_worker
    build:
      context: ./docker/php
    command: /var/www/docker/php/start-workers.sh
    volumes:
      - .:/var/www
      - ./storage/app/files:/var/www/storage/app/files
    environment:
      - QUEUE_WORKERS=${QUEUE_WORKERS:-10}
      - QUEUE_WORKER_TRIES=${QUEUE_WORKER_TRIES:-3}
      - QUEUE_WORKER_TIMEOUT=${QUEUE_WORKER_TIMEOUT:-300}
      - QUEUE_WORKER_MEMORY=${QUEUE_WORKER_MEMORY:-256}
      - QUEUE_WORKER_SLEEP=${QUEUE_WORKER_SLEEP:-3}
      - QUEUE_WORKER_MAX_JOBS=${QUEUE_WORKER_MAX_JOBS:-1000}
    networks:
      - app-network
    depends_on:
      - db
      - minio
      - app
    restart: unless-stopped

  nginx:
    container_name: mgr_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    container_name: mgr_db
    image: postgres:15
    environment:
      POSTGRES_DB: email_migration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5455:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  minio:
    container_name: mgr_minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./storage/minio:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
